$background = 130c0c
$onBackground = f9e0dd
$surface = 130c0c
$surfaceDim = 130c0c
$surfaceBright = 372927
$surfaceContainerLowest = 000000
$surfaceContainerLow = 1a1110
$surfaceContainer = 221716
$surfaceContainerHigh = 291d1b
$surfaceContainerHighest = 302221
$onSurface = f9e0dd
$surfaceVariant = 302221
$onSurfaceVariant = bca6a4
$outline = 84716f
$outlineVariant = 554442
$inverseSurface = fff8f7
$inverseOnSurface = 5d5351
$shadow = 000000
$scrim = 000000
$surfaceTint = f9b6af
$primary = f9b6af
$primaryDim = eaa9a2
$onPrimary = 61332f
$primaryContainer = 764540
$onPrimaryContainer = ffdbd7
$inversePrimary = 85514c
$primaryFixed = ffbbb4
$primaryFixedDim = f0aea7
$onPrimaryFixed = 4e2420
$onPrimaryFixedVariant = 70403b
$secondary = e7bdb8
$secondaryDim = d8afab
$onSecondary = 563936
$secondaryContainer = 513431
$onSecondaryContainer = dfb6b1
$secondaryFixed = ffdad6
$secondaryFixedDim = f6cac6
$onSecondaryFixed = 553835
$onSecondaryFixedVariant = 745350
$tertiary = ffd9ae
$tertiaryDim = f9c98e
$onTertiary = 6b491a
$tertiaryContainer = f9c98e
$onTertiaryContainer = 614112
$tertiaryFixed = f9c98e
$tertiaryFixedDim = eabc82
$onTertiaryFixed = 4b2e01
$onTertiaryFixedVariant = 6b4a1b
$error = f97386
$errorDim = c44b5f
$onError = 490013
$errorContainer = 871c34
$onErrorContainer = ff97a3
$primaryPaletteKeyColor = a16963
$secondaryPaletteKeyColor = 926f6b
$tertiaryPaletteKeyColor = 96703d
$neutralPaletteKeyColor = 807473
$neutralVariantPaletteKeyColor = 867371
$errorPaletteKeyColor = c74d61
$primary_paletteKeyColor = a16963
$secondary_paletteKeyColor = 926f6b
$tertiary_paletteKeyColor = 96703d
$neutral_paletteKeyColor = 807473
$neutral_variant_paletteKeyColor = 867371
$term0 = 353434
$term1 = ff554a
$term2 = ffbda1
$term3 = ffdfd6
$term4 = b9ab66
$term5 = f18f8f
$term6 = ffba92
$term7 = efd2ca
$term8 = b49e98
$term9 = ff8578
$term10 = ffd4c3
$term11 = fff1ed
$term12 = dcbc93
$term13 = ffa8a5
$term14 = ffd2bb
$term15 = ffffff
$rosewater = ffeeeb
$flamingo = ffd9d6
$pink = ffd2d3
$mauve = ffa8b5
$red = ff9794
$maroon = f9aaa6
$peach = ffbeb1
$yellow = ffede8
$green = ffd8c3
$teal = ffdb94
$sky = ebd1ff
$sapphire = f2b2f2
$blue = ffa1bf
$lavender = ffbaca
$klink = bf6ba0
$klinkSelection = bf6ba0
$kvisited = ce5b6e
$kvisitedSelection = ce5b6d
$knegative = ec534f
$knegativeSelection = ec534e
$kneutral = ff8973
$kneutralSelection = ff8973
$kpositive = fd8c2a
$kpositiveSelection = fd8c2a
$text = f9e0dd
$subtext1 = bca6a4
$subtext0 = 84716f
$overlay2 = 746361
$overlay1 = 635352
$overlay0 = 534645
$surface2 = 443837
$surface1 = 352a2a
$surface0 = 241b1b
$base = 130c0c
$mantle = 130c0c
$crust = 120b0b
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
