shell fish
font_family JetBrainsMono Nerd Font
font_size 12
window_padding_width 20
hide_window_decorations yes
cursor_shape beam
include modesty-effects.conf
cursor_blink_interval 0
include modesty-generated.conf
