#!/usr/bin/env python3
"""Convert vendored Lucide SVG elements into independent native Qt subpaths."""
import json
import xml.etree.ElementTree as ET
from pathlib import Path
ROOT=Path(__file__).resolve().parent.parent
FOLDER=ROOT/'assets/icons/lucide'
manifest=json.loads((FOLDER/'manifest.json').read_text())
def outline(path):
    parts=[]
    for e in ET.parse(path).getroot():
        tag=e.tag.split('}')[-1];a=e.attrib
        def n(k,default=0):return float(a.get(k,default))
        if tag=='path':parts.append(a['d'])
        elif tag in ('circle','ellipse'):
            x=n('cx');y=n('cy');rx=n('r') if tag=='circle' else n('rx');ry=n('r') if tag=='circle' else n('ry')
            parts.append(f'M{x-rx} {y}a{rx} {ry} 0 1 0 {rx*2} 0a{rx} {ry} 0 1 0 {-rx*2} 0')
        elif tag=='line':parts.append(f'M{n("x1")} {n("y1")}L{n("x2")} {n("y2")}')
        elif tag in ('polyline','polygon'):parts.append('M'+a['points']+('Z' if tag=='polygon' else ''))
        elif tag=='rect':
            x=n('x');y=n('y');w=n('width');h=n('height');r=min(n('rx'),w/2,h/2)
            parts.append(f'M{x+r} {y}H{x+w-r}Q{x+w} {y} {x+w} {y+r}V{y+h-r}Q{x+w} {y+h} {x+w-r} {y+h}H{x+r}Q{x} {y+h} {x} {y+h-r}V{y+r}Q{x} {y} {x+r} {y}Z')
        else:raise ValueError(f'Unsupported SVG element: {tag}')
    # Each SVG element starts in a fresh coordinate space. Its initial relative
    # moveto must not inherit the end position of the previous element.
    return ' '.join('M0 0 '+part for part in parts)
paths={key:outline(FOLDER/(name+'.svg')) for key,name in manifest['mapping'].items()}
paths['earbuds']='M7 3C4 3 3 5 3 7s1 4 4 4v8a1.5 1.5 0 0 0 3 0V7c0-2-1-4-3-4ZM17 3c3 0 4 2 4 4s-1 4-4 4v8a1.5 1.5 0 0 1-3 0V7c0-2 1-4 3-4M5 6v2M19 6v2'
for alias,key in {'notifications_none':'notifications','notifications_paused':'do_not_disturb_on','network_wifi':'wifi','network_wifi_1_bar':'wifi','network_wifi_2_bar':'wifi','network_wifi_3_bar':'wifi'}.items():paths[alias]=paths[key]
(ROOT/'components/ControlGlyphs.js').write_text('.pragma library\n// Lucide '+manifest['commit']+'. See assets/icons/lucide/LICENSE.\n// Generated by scripts/build-icons.py.\nvar paths = '+json.dumps(paths,indent=2)+';\n')
print(f'Built {len(paths)} icon mappings')
